version: "2"

linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - errname
    - exhaustive
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - makezero
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
