linters:
  fast: false
  enable:
    - bodyclose
    - errcheck
    - exhaustive
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - prealloc
    - predeclared
    - asciicheck
    - revive
    - makezero
    - dupl
    - errname
    - sqlclosecheck
    - sloglint

run:
  deadline: 5m
  issues-exit-code: 1
  tests: false
  go: '1.24.3'

output:
  formats:
    - format: "colored-line-number"
  print-issued-lines: true
  print-linter-name: true

issues:
  fix: true
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true